### PR TITLE
Move point

### PR DESCRIPTION
**Pull request by antoniolocandro**
added basic move point functionality, added:

point-move
dms-move

possibly a way to optimize this can be done

### CODE REVIEW

**Comment by NathanW2** [comment]
Thanks I will review this week sometime

**Comment by antoniolocandro** [comment]
I'm sure you will find something that needs a fix but that's ok I'm learning

--- Original Message ---

**Comment by NathanW2** [comment]
My only thoughts are at the moment if it should be a single function that can tell the difference between the formats or two functions like this

`feature-move-dms`
`feature-move`

that you can alias to something else like `move-dms` if you wanted to. The main reason for the order was so that all the feature commands can be found by typing `feat` and auto complete will find them all for you.

**Comment by NathanW2** [comment]
@antoniolocandro how do you feel about that comment?

**Comment by antoniolocandro** [comment]
Im ok with it, don't know what would it be required to achieve it though

--- Original Message ---

**Comment by NathanW2** [comment]
Merged and updated the functions in `feature_commands.py`.  They are now called `feature-move-dms` and `feature-move` but there is also a alias called `move-dms`.  They also work on the full selection not just the first feature now.

**Pull request merged**
